CREATE TABLE IF NOT EXISTS USERS (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    PASSWORD CHAR(60),

    EMAIL VARCHAR(320),     -- tech spec

    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),

    PRONOUNS VARCHAR(15), 

    BIRTHDAY DATE,

    ROLE USER_ROLES DEFAULT 'USER',

    JOINED TIMESTAMP NOT NULL DEFAULT NOW(),

    ADDRESSLINEONE TEXT,
    ADDRESSLINETWO TEXT,
    CITY TEXT,
    STATE TEXT,
    ZIP BIGINT,

    CONSTRAINT unique_user_email UNIQUE (EMAIL)
);
