"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authJwt_1 = require("../middleware/authJwt");
const loginController = require("../controllers/auth/login");
const adminController = require("../controllers/auth/admin");
const authRouter = (0, express_1.Router)();
authRouter.post('/login', loginController.authLogin);
authRouter.post('/signup', loginController.authSignUp);
authRouter.post('/admin', [authJwt_1.verifyToken], adminController.authAdmin);
module.exports = authRouter;
